export const KIND_LABELS: Readonly<Record<string,string>>;
export const TERMINAL_STATES: readonly string[];
export const ASSETS: readonly {id:string;name:string;symbol:string}[];
export const TEMPLATES: readonly {id:string;label:string;description:string}[];
export function assetName(id:unknown):string;
export function shortAddress(address:unknown):string;
export function money(value:unknown,currency?:string):string;
export function percent(value:unknown,signed?:boolean):string;
export function count(value:unknown):string;
export function dateTime(value:unknown):string;
export function dateOnly(value:unknown):string;
export function age(value:string,now?:number):string;
export function sourceName(value:string):string;
export function safeExternalUrl(value:unknown):string|null;
export function safeLoopbackUrl(value:unknown):string|null;
export function observations(evidence:unknown):Array<Record<string,unknown>>;
export function stateLabel(state:string):string;
export function progressText(run:unknown,kind:string):string;
export function inferTask(question:unknown):{kind:string;account?:string;asset?:string};
export function metricsFor(kind:string,result:unknown):Array<{label:string;value:string;unit?:string;note:string;negative?:boolean}>;
export const ERROR_COPY: Readonly<Record<string,string>>;
export function errorMessage(error:unknown):string;
